// ui-platform/packages/react/src/components/badge/Badge.tsx
import React, { forwardRef, useEffect, useRef } from 'react';

export interface UiBadgeProps {
  /** Visual style variant of the badge */
  variant?: 'solid' | 'soft' | 'outline';
  /** Color theme of the badge */
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
  /** Size of the badge */
  size?: 'sm' | 'md' | 'lg';
  /** Shape of the badge */
  shape?: 'rounded' | 'pill';
  /** Show as a dot indicator (status indicator) */
  dot?: boolean;
  /** Show remove button */
  removable?: boolean;
  /** Disable the badge */
  disabled?: boolean;
  /** Callback when remove button is clicked */
  onRemove?: () => void;
  /** Badge icon */
  icon?: React.ReactNode;
  /** Badge content */
  children?: React.ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** HTML data attributes */
  [key: `data-${string}`]: string | number | boolean | undefined;
}

export interface UiBadgeRef {
  element: HTMLElement | null;
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'ui-badge': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        variant?: 'solid' | 'soft' | 'outline';
        color?: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
        size?: 'sm' | 'md' | 'lg';
        shape?: 'rounded' | 'pill';
        dot?: boolean;
        removable?: boolean;
        disabled?: boolean;
      };
    }
  }
}

export const Badge = forwardRef<UiBadgeRef, UiBadgeProps>(
  (
    {
      variant = 'solid',
      color = 'primary',
      size = 'md',
      shape = 'rounded',
      dot = false,
      removable = false,
      disabled = false,
      onRemove,
      icon,
      children,
      className,
      ...rest
    },
    ref,
  ) => {
    const innerRef = useRef<HTMLElement>(null);

    // Expose imperative handle
    useEffect(() => {
      if (typeof ref === 'function') {
        ref({ element: innerRef.current });
      } else if (ref) {
        ref.current = { element: innerRef.current };
      }
    }, [ref]);

    // Sync props to web component
    useEffect(() => {
      const el = innerRef.current as any;
      if (!el) return;

      el.variant = variant;
      el.color = color;
      el.size = size;
      el.shape = shape;
      el.dot = dot;
      el.removable = removable;
      el.disabled = disabled;
    }, [variant, color, size, shape, dot, removable, disabled]);

    // Setup event listeners
    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;

      const handleRemove = () => {
        onRemove?.();
      };

      el.addEventListener('remove', handleRemove);

      return () => {
        el.removeEventListener('remove', handleRemove);
      };
    }, [onRemove]);

    return React.createElement(
      'ui-badge' as any,
      {
        ref: innerRef,
        class: className,
        variant,
        color,
        size,
        shape,
        dot,
        removable,
        disabled,
        ...rest,
      },
      icon && React.createElement('span', { slot: 'icon' }, icon),
      !dot && children,
    );
  },
);

Badge.displayName = 'Badge';

// ui-platform/packages/angular/projects/ui-lib/src/lib/badge/badge.component.ts
import { Component, ChangeDetectionStrategy, input, output, ElementRef, inject, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';

@Component({
  selector: 'ui-badge-wrapper',
  standalone: true,
  templateUrl: './badge.component.html',
  styleUrls: ['./badge.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: BadgeComponent,
      multi: true,
    },
  ],
})
export class BadgeComponent implements ControlValueAccessor {
  private hostElement = inject(ElementRef);

  // === INPUTS ===

  /** Visual style variant of the badge */
  variant = input<'solid' | 'soft' | 'outline'>('solid');

  /** Color theme of the badge */
  color = input<'primary' | 'success' | 'warning' | 'danger' | 'neutral'>('primary');

  /** Size of the badge */
  size = input<'sm' | 'md' | 'lg'>('md');

  /** Shape of the badge */
  shape = input<'rounded' | 'pill'>('rounded');

  /** Show as a dot indicator (status indicator) */
  dot = input(false);

  /** Show remove button */
  removable = input(false);

  /** Disable the badge */
  disabled = input(false);

  // === OUTPUTS ===

  /** Callback when remove button is clicked */
  remove = output<void>();

  // === CONTROL VALUE ACCESSOR ===

  private onChange: (value: any) => void = () => {};
  private onTouched: () => void = () => {};
  private value: any = null;

  writeValue(value: any): void {
    this.value = value;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    // The disabled input handles this via property binding
  }

  // === METHODS ===

  handleRemove(): void {
    this.remove.emit();
    this.onChange(null);
    this.onTouched();
  }
}

<ui-badge
  [variant]="variant()"
  [color]="color()"
  [size]="size()"
  [shape]="shape()"
  [dot]="dot()"
  [removable]="removable()"
  [disabled]="disabled()"
  (remove)="handleRemove()"
>
  <ng-content select="[badge-icon]" slot="icon"></ng-content>
  <ng-content></ng-content>
</ui-badge>
