// ui-platform/packages/react/src/components/date-picker/DatePicker.tsx
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";

type DateRange = { start: Date; end: Date };
type DatePickerValue = Date | DateRange | undefined;
type DatePickerMode = "single" | "range";

type CustomParser = {
  regex: RegExp;
  parse: (match: RegExpMatchArray) => Date | DateRange;
};

export type DatePickerProps = {
  value?: DatePickerValue;
  defaultValue?: DatePickerValue;
  mode?: DatePickerMode;
  placeholder?: string;
  disabled?: boolean;
  loading?: boolean;
  readonly?: boolean;
  open?: boolean;
  defaultOpen?: boolean;
  minDate?: Date;
  maxDate?: Date;
  minYear?: number;
  maxYear?: number;
  showIcon?: boolean;
  iconOnly?: boolean;
  icon?: string;
  label?: string;
  showActions?: boolean;
  search?: boolean;
  customParsers?: CustomParser[];
  debounce?: number;
  onChange?: (date: Date | DateRange) => void;
  onApply?: (date: Date | DateRange) => void;
  onCancel?: () => void;
  onInputChange?: (value: string) => void;
  onOpenChange?: (open: boolean) => void;
  onInvalidInput?: (value: string) => void;
  onFocus?: () => void;
  onBlur?: () => void;
};

export const DatePicker = forwardRef<HTMLElement, DatePickerProps>(
  (
    {
      value,
      defaultValue,
      mode = "single",
      placeholder,
      disabled,
      loading,
      readonly,
      open,
      defaultOpen,
      minDate,
      maxDate,
      minYear,
      maxYear,
      showIcon = true,
      iconOnly = false,
      icon,
      label,
      showActions = false,
      search = false,
      customParsers,
      debounce = 220,
      onChange,
      onApply,
      onCancel,
      onInputChange,
      onOpenChange,
      onInvalidInput,
      onFocus,
      onBlur,
    },
    forwardedRef,
  ) => {
    const ref = useRef<any>(null);
    const isControlled = value !== undefined;
    const [internalValue, setInternalValue] = useState<DatePickerValue>(defaultValue);
    const currentValue = isControlled ? value : internalValue;

    useImperativeHandle(forwardedRef, () => ref.current);

    useEffect(() => {
      const el = ref.current;
      if (!el) return;
      el.value = currentValue;
      el.mode = mode;
      el.placeholder = placeholder ?? "Enter date (e.g. 1 Jan 2020)";
      el.disabled = !!disabled;
      el.loading = !!loading;
      el.readonly = !!readonly;
      el.open = open;
      el.defaultOpen = !!defaultOpen;
      el.minDate = minDate;
      el.maxDate = maxDate;
      el.minYear = minYear;
      el.maxYear = maxYear;
      el.showIcon = !!showIcon;
      el.iconOnly = !!iconOnly;
      el.icon = icon;
      el.label = label;
      el.showActions = !!showActions;
      el.search = !!search;
      el.customParsers = customParsers;
      el.debounce = debounce;
    }, [
      currentValue,
      mode,
      placeholder,
      disabled,
      loading,
      readonly,
      open,
      defaultOpen,
      minDate,
      maxDate,
      minYear,
      maxYear,
      showIcon,
      iconOnly,
      icon,
      label,
      showActions,
      search,
      customParsers,
      debounce,
    ]);

    useEffect(() => {
      const el = ref.current;
      if (!el) return;

      const handleChange = (e: any) => {
        const nextValue = e.detail as Date | DateRange;
        if (!isControlled) setInternalValue(nextValue);
        onChange?.(nextValue);
      };
      const handleInputChange = (e: any) => onInputChange?.(e.detail as string);
      const handleApply = (e: any) => onApply?.(e.detail as Date | DateRange);
      const handleCancel = () => onCancel?.();
      const handleOpenChange = (e: any) => onOpenChange?.(!!e.detail);
      const handleInvalidInput = (e: any) => onInvalidInput?.(e.detail as string);
      const handleFocus = () => onFocus?.();
      const handleBlur = () => onBlur?.();

      el.addEventListener("onChange", handleChange);
      el.addEventListener("onInputChange", handleInputChange);
      el.addEventListener("onApply", handleApply);
      el.addEventListener("onCancel", handleCancel);
      el.addEventListener("onOpenChange", handleOpenChange);
      el.addEventListener("onInvalidInput", handleInvalidInput);
      el.addEventListener("onFocus", handleFocus);
      el.addEventListener("onBlur", handleBlur);

      return () => {
        el.removeEventListener("onChange", handleChange);
        el.removeEventListener("onInputChange", handleInputChange);
        el.removeEventListener("onApply", handleApply);
        el.removeEventListener("onCancel", handleCancel);
        el.removeEventListener("onOpenChange", handleOpenChange);
        el.removeEventListener("onInvalidInput", handleInvalidInput);
        el.removeEventListener("onFocus", handleFocus);
        el.removeEventListener("onBlur", handleBlur);
      };
    }, [isControlled, onApply, onBlur, onCancel, onChange, onFocus, onInputChange, onInvalidInput, onOpenChange]);

    return React.createElement("ui-date-picker", { ref });
  },
);

DatePicker.displayName = "DatePicker";

// ui-platform/packages/angular/projects/ui-lib/src/lib/date-picker/date-picker.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  Directive,
  Optional,
  Self,
  computed,
  forwardRef,
  input,
  output,
  signal,
} from '@angular/core';
import {
  AbstractControl,
  ControlValueAccessor,
  NG_VALIDATORS,
  NG_VALUE_ACCESSOR,
  NgControl,
  ValidationErrors,
  Validator,
} from '@angular/forms';
import { ensureCustomElements } from '../register-custom-elements';

type DateRange = { start: Date; end: Date };
type DatePickerValue = Date | DateRange | null;

ensureCustomElements();

@Component({
  selector: 'ui-date-picker-angular',
  standalone: true,
  templateUrl: './date-picker.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => UiDatePickerComponent),
      multi: true,
    },
    {
      provide: NG_VALIDATORS,
      useExisting: forwardRef(() => UiDatePickerComponent),
      multi: true,
    },
  ],
  host: {
    '[class.ng-invalid]': 'isInvalid()',
    '[class.ng-touched]': 'isTouched()',
    '[class.ng-dirty]': 'isDirty()',
  },
})
export class UiDatePickerComponent implements ControlValueAccessor, Validator {
  constructor(@Optional() @Self() private readonly ngControl: NgControl | null) {
    if (this.ngControl) this.ngControl.valueAccessor = this;
  }

  value = signal<DatePickerValue>(null);
  disabledState = signal(false);
  touched = signal(false);

  mode = input<'single' | 'range'>('single');
  placeholder = input<string>('Enter date (e.g. 1 Jan 2020)');
  disabled = input<boolean>(false);
  loading = input<boolean>(false);
  readonly = input<boolean>(false);
  open = input<boolean | undefined>(undefined);
  defaultOpen = input<boolean>(false);
  minDate = input<Date | undefined>(undefined);
  maxDate = input<Date | undefined>(undefined);
  minYear = input<number | undefined>(undefined);
  maxYear = input<number | undefined>(undefined);
  showIcon = input<boolean>(true);
  iconOnly = input<boolean>(false);
  icon = input<string | undefined>(undefined);
  label = input<string | undefined>(undefined);
  showActions = input<boolean>(false);
  search = input<boolean>(false);
  customParsers = input<any[] | undefined>(undefined);
  debounce = input<number>(220);

  onInputChange = output<string>();
  onOpenChange = output<boolean>();
  onInvalidInput = output<string>();
  onApply = output<Date | DateRange>();
  onCancel = output<void>();
  onFocus = output<void>();
  onBlur = output<void>();
  changed = output<Date | DateRange>();

  private onChange: (value: DatePickerValue) => void = () => {};
  private onTouched: () => void = () => {};

  readonly isInvalid = computed(() => !!this.ngControl?.invalid);
  readonly isTouched = computed(() => this.touched() || !!this.ngControl?.touched);
  readonly isDirty = computed(() => !!this.ngControl?.dirty);

  writeValue(value: DatePickerValue): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: DatePickerValue) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabledState.set(isDisabled);
  }

  validate(_control: AbstractControl): ValidationErrors | null {
    return null;
  }

  handleChange(event: Event): void {
    const detail = (event as CustomEvent<Date | DateRange>).detail;
    this.value.set(detail);
    this.onChange(detail);
    this.changed.emit(detail);
  }

  handleInputChange(event: Event): void {
    this.onInputChange.emit((event as CustomEvent<string>).detail);
  }

  handleOpenChange(event: Event): void {
    this.onOpenChange.emit(!!(event as CustomEvent<boolean>).detail);
  }

  handleApply(event: Event): void {
    this.onApply.emit((event as CustomEvent<Date | DateRange>).detail);
  }

  handleCancel(): void {
    this.onCancel.emit();
  }

  handleInvalidInput(event: Event): void {
    this.onInvalidInput.emit((event as CustomEvent<string>).detail);
  }

  handleFocus(): void {
    this.onFocus.emit();
  }

  handleBlur(): void {
    this.touched.set(true);
    this.onTouched();
    this.onBlur.emit();
  }
}

@Directive({
  selector: '[uiDatePicker]',
  standalone: true,
  host: {
    '[attr.data-ui-date-picker]': '"true"',
  },
})
export class UiDatePickerDirective {}

<ui-date-picker
  [value]="value()"
  [mode]="mode()"
  [placeholder]="placeholder()"
  [disabled]="disabled() || disabledState()"
  [loading]="loading()"
  [readonly]="readonly()"
  [open]="open()"
  [defaultOpen]="defaultOpen()"
  [minDate]="minDate()"
  [maxDate]="maxDate()"
  [minYear]="minYear()"
  [maxYear]="maxYear()"
  [showIcon]="showIcon()"
  [iconOnly]="iconOnly()"
  [icon]="icon()"
  [label]="label()"
  [showActions]="showActions()"
  [search]="search()"
  [customParsers]="customParsers()"
  [debounce]="debounce()"
  (onChange)="handleChange($event)"
  (onInputChange)="handleInputChange($event)"
  (onApply)="handleApply($event)"
  (onCancel)="handleCancel()"
  (onOpenChange)="handleOpenChange($event)"
  (onInvalidInput)="handleInvalidInput($event)"
  (onFocus)="handleFocus()"
  (onBlur)="handleBlur()"
></ui-date-picker>
