// ui-platform/packages/angular/projects/ui-lib/src/lib/spinner/spinner.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  inject,
  input,
  OnDestroy,
  OnInit,
  output,
} from '@angular/core';
import { ensureCustomElements } from '../register-custom-elements';

ensureCustomElements();

export type SpinnerVariant = 'circular' | 'dots' | 'bars' | 'pulse' | 'ring';
export type SpinnerSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type SpinnerSpeed = 'slow' | 'normal' | 'fast';

/**
 * Modern Angular Spinner Component
 * Standalone component with signals-based inputs/outputs
 * Wraps ui-spinner web component
 *
 * @usage
 * <ui-spinner-angular
 *   variant="circular"
 *   size="md"
 *   [loading]="isLoading"
 *   [overlay]="false"
 *   label="Loading..."
 *   (shown)="onShown()"
 *   (hidden)="onHidden()"
 * />
 */
@Component({
  selector: 'ui-spinner-angular',
  templateUrl: './spinner.component.html',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class.ui-spinner-ng]': 'true',
  },
})
export class SpinnerComponent implements OnInit, OnDestroy {
  private el = inject(ElementRef<HTMLElement>);
  private eventListeners: (() => void)[] = [];

  // === SIGNAL INPUTS ===

  /** Animation variant style */
  variant = input<SpinnerVariant>('circular');

  /** Size of the spinner */
  size = input<SpinnerSize | number>('md');

  /** Animation speed */
  speed = input<SpinnerSpeed | number>('normal');

  /** Primary color for the spinner */
  color = input<string | undefined>(undefined);

  /** Background/track color */
  trackColor = input<string | undefined>(undefined);

  /** Whether the spinner is visible */
  loading = input<boolean>(true);

  /** Display as fullscreen/container overlay */
  overlay = input<boolean>(false);

  /** Display inline with text (no flex center) */
  inline = input<boolean>(false);

  /** Center the spinner in its container */
  center = input<boolean>(false);

  /** Primary label text (e.g., "Loading...") */
  label = input<string | undefined>(undefined);

  /** Secondary label text (e.g., "Please wait") */
  subLabel = input<string | undefined>(undefined);

  // === OUTPUTS ===

  /** Emitted when spinner becomes visible */
  shown = output<void>();

  /** Emitted when spinner becomes hidden */
  hidden = output<void>();

  // === LIFECYCLE ===

  ngOnInit(): void {
    this.setupEventListeners();
    this.syncPropsToWebComponent();
  }

  ngOnDestroy(): void {
    this.eventListeners.forEach((remove) => remove());
  }

  // === PRIVATE METHODS ===

  private setupEventListeners(): void {
    const spinner = this.el.nativeElement.querySelector('ui-spinner');
    if (!spinner) return;

    // Shown event
    const shownHandler = () => this.shown.emit();
    spinner.addEventListener('shown', shownHandler);
    this.eventListeners.push(() =>
      spinner.removeEventListener('shown', shownHandler)
    );

    // Hidden event
    const hiddenHandler = () => this.hidden.emit();
    spinner.addEventListener('hidden', hiddenHandler);
    this.eventListeners.push(() =>
      spinner.removeEventListener('hidden', hiddenHandler)
    );
  }

  private syncPropsToWebComponent(): void {
    // Props are synced via template binding in spinner.component.html
  }
}

<ui-spinner
  [variant]="variant()"
  [size]="size()"
  [speed]="speed()"
  [color]="color()"
  [trackColor]="trackColor()"
  [loading]="loading()"
  [overlay]="overlay()"
  [inline]="inline()"
  [center]="center()"
  [label]="label()"
  [subLabel]="subLabel()"
></ui-spinner>

// ui-platform/packages/react/src/components/spinner/Spinner.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useCallback,
  type ReactNode,
} from "react";

// === TYPES ===

export type SpinnerVariant = 'circular' | 'dots' | 'bars' | 'pulse' | 'ring';
export type SpinnerSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type SpinnerSpeed = 'slow' | 'normal' | 'fast';

export interface UiSpinnerProps {
  /** Animation variant style */
  variant?: SpinnerVariant;

  /** Size of the spinner */
  size?: SpinnerSize | number;

  /** Animation speed */
  speed?: SpinnerSpeed | number;

  /** Primary color for the spinner */
  color?: string;

  /** Background/track color */
  trackColor?: string;

  /** Whether the spinner is visible */
  loading?: boolean;

  /** Display as fullscreen/container overlay */
  overlay?: boolean;

  /** Display inline with text (no flex center) */
  inline?: boolean;

  /** Center the spinner in its container */
  center?: boolean;

  /** Primary label text (e.g., "Loading...") */
  label?: string;

  /** Secondary label text (e.g., "Please wait") */
  subLabel?: string;

  /** Shown event handler */
  onShown?: () => void;

  /** Hidden event handler */
  onHidden?: () => void;

  /** Additional CSS classes */
  className?: string;

  /** HTML data attributes */
  [key: `data-${string}`]: string | number | boolean | undefined;
}

export interface UiSpinnerRef {
  /** Reference to the underlying ui-spinner element */
  readonly element: HTMLElement | null;
}

// === COMPONENT ===

/**
 * React Spinner Component
 * Modern wrapper around ui-spinner web component
 *
 * @example
 * ```tsx
 * <UiSpinner
 *   variant="circular"
 *   size="md"
 *   loading={true}
 *   label="Loading..."
 * />
 * ```
 */
export const UiSpinner = forwardRef<UiSpinnerRef, UiSpinnerProps>(
  (
    {
      variant = 'circular',
      size = 'md',
      speed = 'normal',
      color,
      trackColor,
      loading = true,
      overlay = false,
      inline = false,
      center = false,
      label,
      subLabel,
      onShown,
      onHidden,
      className,
      ...rest
    },
    ref,
  ) => {
    const innerRef = useRef<HTMLElement>(null);

    // Expose imperative handle
    useImperativeHandle(ref, () => ({
      get element() {
        return innerRef.current;
      },
    }));

    // Sync props to web component
    useEffect(() => {
      const el = innerRef.current as (HTMLElement & {
        variant?: SpinnerVariant;
        size?: SpinnerSize | number;
        speed?: SpinnerSpeed | number;
        color?: string;
        trackColor?: string;
        loading?: boolean;
        overlay?: boolean;
        inline?: boolean;
        center?: boolean;
        label?: string;
        subLabel?: string;
      }) | null;
      if (!el) return;

      el.variant = variant;
      el.size = size;
      el.speed = speed;
      if (color !== undefined) el.color = color;
      if (trackColor !== undefined) el.trackColor = trackColor;
      el.loading = loading;
      el.overlay = overlay;
      el.inline = inline;
      el.center = center;
      if (label !== undefined) el.label = label;
      if (subLabel !== undefined) el.subLabel = subLabel;
    }, [variant, size, speed, color, trackColor, loading, overlay, inline, center, label, subLabel]);

    // Event handlers
    const handleShown = useCallback(() => {
      onShown?.();
    }, [onShown]);

    const handleHidden = useCallback(() => {
      onHidden?.();
    }, [onHidden]);

    // Bind event listeners
    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;

      el.addEventListener("shown", handleShown);
      el.addEventListener("hidden", handleHidden);

      return () => {
        el.removeEventListener("shown", handleShown);
        el.removeEventListener("hidden", handleHidden);
      };
    }, [handleShown, handleHidden]);

    return (
      <ui-spinner
        ref={innerRef}
        className={className}
        {...rest}
      />
    );
  },
);

UiSpinner.displayName = "UiSpinner";
