// ui-platform/packages/react/src/components/dropdown/Dropdown.tsx
import {
  forwardRef,
  useEffect,
  useRef,
  useState,
  useImperativeHandle,
} from "react";

export type DropdownOption = {
  label: string;
  value: any;
  disabled?: boolean;
  group?: string;
};

export type DropdownMode = 'single' | 'multiple';
export type DropdownVariant = 'input' | 'button' | 'icon-only';

type UiDropdownProps = {
  value?: any;
  defaultValue?: any;
  options: DropdownOption[];
  mode?: DropdownMode;
  variant?: DropdownVariant;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
  loading?: boolean;
  searchable?: boolean;
  clearable?: boolean;
  open?: boolean;
  selectAll?: boolean;
  minWidth?: string;
  maxWidth?: string;
  maxHeight?: string;
  onChange?: (value: any) => void;
  onOpenChange?: (open: boolean) => void;
  onSearch?: (query: string) => void;
};

export const UiDropdown = forwardRef<HTMLElement, UiDropdownProps>(
  (
    {
      value,
      defaultValue = null,
      options = [],
      mode = 'single',
      variant = 'input',
      placeholder = 'Select...',
      label,
      disabled = false,
      loading = false,
      searchable = false,
      clearable = false,
      open = false,
      selectAll = false,
      minWidth = '200px',
      maxWidth = 'none',
      maxHeight = '300px',
      onChange,
      onOpenChange,
      onSearch,
    },
    forwardedRef,
  ) => {
    const ref = useRef<any>(null);

    // Controlled vs uncontrolled
    const isControlled = value !== undefined;
    const [internalValue, setInternalValue] = useState(defaultValue);
    const [internalOpen, setInternalOpen] = useState(open);

    const currentValue = isControlled ? value : internalValue;
    const currentOpen = isControlled ? open : internalOpen;

    // Stable refs
    const onChangeRef = useRef(onChange);
    const onOpenChangeRef = useRef(onOpenChange);
    const onSearchRef = useRef(onSearch);

    useEffect(() => {
      onChangeRef.current = onChange;
      onOpenChangeRef.current = onOpenChange;
      onSearchRef.current = onSearch;
    });

    // Sync props → Web Component
    useEffect(() => {
      const el = ref.current;
      if (!el) return;

      el.value = currentValue ?? null;
      el.defaultValue = defaultValue ?? null;
      el.options = options;
      el.mode = mode;
      el.variant = variant;
      el.placeholder = placeholder;
      el.label = label ?? '';
      el.disabled = disabled;
      el.loading = loading;
      el.searchable = searchable;
      el.clearable = clearable;
      el.open = currentOpen;
      el.selectAll = selectAll;
      el.minWidth = minWidth;
      el.maxWidth = maxWidth;
      el.maxHeight = maxHeight;
    }, [
      currentValue,
      defaultValue,
      options,
      mode,
      variant,
      placeholder,
      label,
      disabled,
      loading,
      searchable,
      clearable,
      currentOpen,
      selectAll,
      minWidth,
      maxWidth,
      maxHeight,
    ]);

    // Events
    useEffect(() => {
      const el = ref.current;
      if (!el) return;

      const handleValueChange = (e: any) => {
        const val = e.detail;

        if (!isControlled) {
          setInternalValue(val);
        }

        onChangeRef.current?.(val);
      };

      const handleOpenChange = (e: any) => {
        const isOpen = e.detail;

        if (!isControlled) {
          setInternalOpen(isOpen);
        }

        onOpenChangeRef.current?.(isOpen);
      };

      const handleSearch = (e: any) => {
        const query = e.detail;
        onSearchRef.current?.(query);
      };

      el.addEventListener("valueChange", handleValueChange);
      el.addEventListener("openChange", handleOpenChange);
      el.addEventListener("search", handleSearch);

      return () => {
        el.removeEventListener("valueChange", handleValueChange);
        el.removeEventListener("openChange", handleOpenChange);
        el.removeEventListener("search", handleSearch);
      };
    }, [isControlled]);

    useImperativeHandle(forwardedRef, () => ref.current);

    return <ui-dropdown ref={ref}></ui-dropdown>;
  },
);

UiDropdown.displayName = "UiDropdown";

// ui-platform/packages/angular/projects/ui-lib/src/lib/dropdown/dropdown.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  forwardRef,
  input,
  output,
  signal,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { ensureCustomElements } from '../register-custom-elements';

ensureCustomElements();

export type DropdownOption = {
  label: string;
  value: any;
  disabled?: boolean;
  group?: string;
};

export type DropdownMode = 'single' | 'multiple';
export type DropdownVariant = 'input' | 'button' | 'icon-only';

@Component({
  selector: 'ui-dropdown-angular',
  templateUrl: './dropdown.component.html',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => DropdownComponent),
      multi: true,
    },
  ],
})
export class DropdownComponent implements ControlValueAccessor {
  options = input<DropdownOption[]>([]);
  mode = input<DropdownMode>('single');
  variant = input<DropdownVariant>('input');
  placeholder = input<string>('Select...');
  label = input<string | undefined>(undefined);
  disabled = input<boolean>(false);
  loading = input<boolean>(false);
  searchable = input<boolean>(false);
  clearable = input<boolean>(false);
  open = input<boolean>(false);
  selectAll = input<boolean>(false);
  minWidth = input<string>('200px');
  maxWidth = input<string>('none');
  maxHeight = input<string>('300px');

  value = signal<any>(null);
  isDisabled = signal<boolean>(false);
  openChange = output<boolean>();
  search = output<string>();

  onChange = (value: any) => {};
  onTouched = () => {};

  writeValue(value: any): void {
    this.value.set(value ?? null);
  }

  setDisabledState(isDisabled: boolean): void {
    this.isDisabled.set(isDisabled);
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  handleValueChange(event: Event) {
    const value = (event as CustomEvent<any>).detail;

    this.value.set(value);
    this.onChange(value);
  }

  handleOpenChange(event: Event) {
    const isOpen = (event as CustomEvent<boolean>).detail;
    this.openChange.emit(isOpen);
  }

  handleSearch(event: Event) {
    const query = (event as CustomEvent<string>).detail;
    this.search.emit(query);
  }
}

<ui-dropdown
  [value]="value()"
  [options]="options()"
  [mode]="mode()"
  [variant]="variant()"
  [placeholder]="placeholder()"
  [label]="label()"
  [disabled]="isDisabled()"
  [loading]="loading()"
  [searchable]="searchable()"
  [clearable]="clearable()"
  [open]="open()"
  [selectAll]="selectAll()"
  [minWidth]="minWidth()"
  [maxWidth]="maxWidth()"
  [maxHeight]="maxHeight()"
  (valueChange)="handleValueChange($event)"
  (openChange)="handleOpenChange($event)"
  (search)="handleSearch($event)"
></ui-dropdown>
