// ui-platform/packages/angular/projects/ui-lib/src/lib/radio/radio.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  Directive,
  forwardRef,
  input,
  output,
} from '@angular/core';
import { ensureCustomElements } from '../register-custom-elements';

ensureCustomElements();

@Component({
  selector: 'ui-radio-angular',
  standalone: true,
  templateUrl: './radio.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UiRadioComponent {
  value = input.required<string>();
  checked = input<boolean>(false);
  disabled = input<boolean>(false);
  required = input<boolean>(false);
  name = input<string | undefined>(undefined);
  error = input<boolean>(false);
  size = input<'sm' | 'md' | 'lg'>('md');
  label = input<string | undefined>(undefined);
  supportingText = input<string | undefined>(undefined);

  uiChange = output<string>();
  uiFocus = output<void>();
  uiBlur = output<void>();

  handleChange(event: Event): void {
    this.uiChange.emit((event as CustomEvent<string>).detail);
  }

  handleFocus(): void {
    this.uiFocus.emit();
  }

  handleBlur(): void {
    this.uiBlur.emit();
  }
}

@Directive({
  selector: '[uiRadio]',
  standalone: true,
  host: {
    '[attr.data-ui-radio]': '"true"',
  },
})
export class UiRadioDirective {}

<ui-radio
  [value]="value()"
  [checked]="checked()"
  [disabled]="disabled()"
  [required]="required()"
  [name]="name()"
  [error]="error()"
  [size]="size()"
  [label]="label()"
  [supportingText]="supportingText()"
  (uiChange)="handleChange($event)"
  (uiFocus)="handleFocus()"
  (uiBlur)="handleBlur()"
>
  @if (label()) {
    <span slot="label">{{ label() }}</span>
  }
  @if (supportingText()) {
    <span slot="supporting">{{ supportingText() }}</span>
  }
  <ng-content />
</ui-radio>

// ui-platform/packages/react/src/components/radio/Radio.tsx
import React, { forwardRef, useEffect, useImperativeHandle, useRef } from "react";

export type RadioProps = {
  value: string;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  error?: boolean;
  size?: 'sm' | 'md' | 'lg';
  label?: string;
  supportingText?: string;
  uiChange?: (value: string) => void;
  uiFocus?: () => void;
  uiBlur?: () => void;
  children?: React.ReactNode;
};

export const Radio = forwardRef<HTMLElement, RadioProps>(
  (
    {
      value,
      checked,
      disabled = false,
      required = false,
      name,
      size = 'md',
      error = false,
      label,
      supportingText,
      uiChange,
      uiFocus,
      uiBlur,
      children,
    },
    forwardedRef,
  ) => {
    const ref = useRef<any>(null);

    useImperativeHandle(forwardedRef, () => ref.current);

    useEffect(() => {
      const el = ref.current;
      if (!el) return;
      
      el.value = value;
      el.checked = !!checked;
      el.disabled = !!disabled;
      el.required = !!required;
      el.size = size;
      el.name = name;
      el.error = !!error;
      el.label = label;
      el.supportingText = supportingText;
    }, [value, checked, disabled, required, name, error, size, label, supportingText]);

    useEffect(() => {
      const el = ref.current;
      if (!el) return;

      const handleChange = (e: any) => uiChange?.(e.detail as string);
      const handleFocus = () => uiFocus?.();
      const handleBlur = () => uiBlur?.();

      el.addEventListener("uiChange", handleChange);
      el.addEventListener("uiFocus", handleFocus);
      el.addEventListener("uiBlur", handleBlur);

      return () => {
        el.removeEventListener("uiChange", handleChange);
        el.removeEventListener("uiFocus", handleFocus);
        el.removeEventListener("uiBlur", handleBlur);
      };
    }, [uiChange, uiFocus, uiBlur]);

    return React.createElement(
      "ui-radio",
      { ref },
      label ? React.createElement("span", { slot: "label" }, label) : null,
      supportingText ? React.createElement("span", { slot: "supporting" }, supportingText) : null,
      children
    );
  },
);

Radio.displayName = "Radio";
