// ui-platform/packages/react/src/components/button-group/ButtonGroup.tsx
import React, {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useCallback,
  useState,
  type ReactNode,
  type MouseEvent as ReactMouseEvent,
  Children,
  cloneElement,
  isValidElement,
} from "react";
import type {
  ButtonGroupOrientation,
  ButtonGroupSelectionMode,
  ButtonGroupVariant,
  ButtonGroupSize,
  ButtonGroupEventDetail,
  IconName,
  ButtonRounded,
} from "@karan9186/core";
import { isButtonSelected, computeNewSelectedValue } from "@karan9186/core";
import { UiButton } from "../button/Button";

// === TYPES ===

export interface UiButtonGroupProps {
  /** Button children to be grouped */
  children?: ReactNode;

  /** Orientation of the button group */
  orientation?: ButtonGroupOrientation;

  /** Gap between buttons */
  gap?: 'xs' | 'sm' | 'md' | 'lg' | 'none';

  /** Variant inheritance for child buttons */
  variant?: ButtonGroupVariant;

  /** Size inheritance for child buttons */
  size?: ButtonGroupSize;

  /** Whether buttons are segmented */
  segmented?: boolean;

  /** Whether the group takes full width */
  fullWidth?: boolean;

  /** Whether the entire group is disabled */
  disabled?: boolean;

  /** Border radius size for the button group */
  rounded?: ButtonRounded;

  /** JSON string array of button objects with value, label, and optional button props */
  buttons?: string;

  /** Whether child buttons are in loading state */
  buttonLoading?: boolean;

  /** Whether to enable click animation on child buttons (press effect) */
  buttonAnimated?: boolean;

  /** Whether child buttons should take full width */
  buttonFullWidth?: boolean;

  /** Selection mode for the button group */
  selectionMode?: 'none' | 'single' | 'multiple';

  /** Current selected value(s) */
  value?: string | string[];

  /** Change event handler */
  onUiChange?: (detail: ButtonGroupEventDetail) => void;

  /** Value change event handler (new API) */
  onValueChange?: (value: string | string[]) => void;

  /** Click event handler (proxy) */
  onUiClick?: (detail: ButtonGroupEventDetail) => void;

  /** Additional CSS classes */
  className?: string;

  /** HTML data attributes */
  [key: `data-${string}`]: string | number | boolean | undefined;
}

export interface UiButtonGroupRef {
  /** Reference to the underlying ui-button-group element */
  readonly element: HTMLElement | null;
  /** Focus the button group */
  focus: () => void;
  /** Blur the button group */
  blur: () => void;
}

// === COMPONENT ===

/**
 * React ButtonGroup Component
 * Modern wrapper around ui-button-group web component
 *
 * @example
 * ```tsx
 * <UiButtonGroup
 *   orientation="horizontal"
 *   selectionMode="single"
 *   value={selectedValue}
 *   onUiChange={(detail) => setSelectedValue(detail.value)}
 * >
 *   <UiButton value="option1">Option 1</UiButton>
 *   <UiButton value="option2">Option 2</UiButton>
 *   <UiButton value="option3">Option 3</UiButton>
 * </UiButtonGroup>
 * ```
 */
export const UiButtonGroup = forwardRef<UiButtonGroupRef, UiButtonGroupProps>(
  (
    {
      children,
      variant = "inherit",
      size = "inherit",
      segmented = false,
      orientation = "horizontal",
      gap = "md",
      fullWidth = false,
      disabled = false,
      rounded = "md",
      buttons,
      buttonLoading = false,
      buttonAnimated = false,
      buttonFullWidth = false,
      selectionMode = "none",
      value,
      onUiChange,
      onValueChange,
      onUiClick,
      className,
      ...rest
    },
    ref,
  ) => {
    const innerRef = useRef<HTMLElement>(null);

    // Expose imperative handle
    useImperativeHandle(ref, () => ({
      get element() {
        return innerRef.current;
      },
      focus: () => innerRef.current?.focus(),
      blur: () => innerRef.current?.blur(),
    }));

    // Sync props to web component
    useEffect(() => {
      const el = innerRef.current as (HTMLElement & {
        variant?: string;
        size?: string;
        segmented?: boolean;
        orientation?: string;
        gap?: string;
        fullWidth?: boolean;
        disabled?: boolean;
        rounded?: string;
        buttons?: string;
        buttonLoading?: boolean;
        buttonAnimated?: boolean;
        buttonFullWidth?: boolean;
        selectionMode?: string;
        value?: string | string[];
      }) | null;
      if (!el) return;

      el.variant = variant;
      el.size = size;
      el.segmented = segmented;
      el.orientation = orientation;
      el.gap = gap;
      el.fullWidth = fullWidth;
      el.disabled = disabled;
      el.rounded = rounded;
      if (buttons !== undefined) el.buttons = buttons;
      el.buttonLoading = buttonLoading;
      el.buttonAnimated = buttonAnimated;
      el.buttonFullWidth = buttonFullWidth;
      el.selectionMode = selectionMode;
      if (value !== undefined) el.value = value;
    }, [variant, size, segmented, orientation, gap, fullWidth, disabled, rounded, buttons, buttonLoading, buttonAnimated, buttonFullWidth, selectionMode, value]);

    // Setup event listeners
    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;

      const handleValueChange = (e: Event) => {
        const customEvent = e as CustomEvent<string | string[]>;
        onValueChange?.(customEvent.detail);
      };

      const handleUiChange = (e: Event) => {
        const customEvent = e as CustomEvent<ButtonGroupEventDetail>;
        onUiChange?.(customEvent.detail);
      };

      const handleUiClick = (e: Event) => {
        const customEvent = e as CustomEvent<ButtonGroupEventDetail>;
        onUiClick?.(customEvent.detail);
      };

      el.addEventListener('valueChange', handleValueChange);
      el.addEventListener('uiChange', handleUiChange);
      el.addEventListener('uiClick', handleUiClick);

      return () => {
        el.removeEventListener('valueChange', handleValueChange);
        el.removeEventListener('uiChange', handleUiChange);
        el.removeEventListener('uiClick', handleUiClick);
      };
    }, [onValueChange, onUiChange, onUiClick]);

    // Apply props to child buttons
    const childrenWithProps = Children.map(children, (child, index) => {
      if (!isValidElement(child)) {
        return child;
      }

      // Only apply props to UiButton components
      if (child.type !== UiButton) {
        return child;
      }

      const total = Children.count(children);
      const isFirst = index === 0;
      const isLast = index === total - 1;

      // Apply variant and size inheritance
      const childProps: Partial<React.ComponentProps<typeof UiButton>> = {};

      if (variant !== 'inherit') {
        childProps.variant = variant;
      }

      if (size !== 'inherit') {
        childProps.size = size;
      }

      if (disabled) {
        childProps.disabled = disabled;
      }

      // Apply segmented styling
      if (segmented) {
        if (isFirst && total > 1) {
          childProps['data-position'] = 'first';
        } else if (isLast && total > 1) {
          childProps['data-position'] = 'last';
        } else if (total > 1) {
          childProps['data-position'] = 'middle';
        }
      }

      return cloneElement(child, childProps);
    });

    // Compute group classes
    const groupClasses = [
      "ui-button-group-react",
      `ui-button-group-react--${orientation}`,
      `ui-button-group-react--gap-${gap}`,
      fullWidth && "ui-button-group-react--full-width",
      segmented && "ui-button-group-react--segmented",
      disabled && "ui-button-group-react--disabled",
      `ui-button-group-react--rounded-${rounded}`,
      className,
    ]
      .filter(Boolean)
      .join(" ");

    // Compute group role
    const groupRole = "group";

    // Compute aria props
    const ariaProps: Record<string, string> = {};

    return (
      <ui-button-group
        ref={innerRef as any}
        className={groupClasses}
        role={groupRole}
        {...ariaProps}
        {...rest}
      >
        {childrenWithProps}
      </ui-button-group>
    );
  },
);

UiButtonGroup.displayName = "UiButtonGroup";

// ui-platform/packages/angular/projects/ui-lib/src/lib/button-group/button-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  Directive,
  ElementRef,
  inject,
  input,
  model,
  output,
  computed,
  contentChildren,
  afterNextRender,
  DestroyRef,
  forwardRef,
  Provider,
} from '@angular/core';
import {
  ControlValueAccessor,
  NG_VALUE_ACCESSOR,
} from '@angular/forms';
import { ensureCustomElements } from '../register-custom-elements';
import type {
  ButtonGroupOrientation,
  ButtonGroupSelectionMode,
  ButtonGroupVariant,
  ButtonGroupSize,
  ButtonGroupEventDetail,
  IconName,
  ButtonRounded,
} from '@karan9186/core';
import { ButtonComponent } from '../button/button.component';

ensureCustomElements();

/**
 * Modern Angular ButtonGroup Component
 * Standalone component with signals-based inputs/outputs
 * Wraps ui-button-group web component
 *
 * @usage
 * <ui-button-group-angular
 *   orientation="horizontal"
 *   selectionMode="single"
 *   [(value)]="selectedValue"
 *   (uiChange)="handleChange($event)"
 * >
 *   <ui-button-angular value="option1">Option 1</ui-button-angular>
 *   <ui-button-angular value="option2">Option 2</ui-button-angular>
 *   <ui-button-angular value="option3">Option 3</ui-button-angular>
 * </ui-button-group-angular>
 */
const BUTTON_GROUP_VALUE_ACCESSOR: Provider = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => ButtonGroupComponent),
  multi: true,
};

@Component({
  selector: 'ui-button-group-angular',
  templateUrl: 'button-group.component.html',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [BUTTON_GROUP_VALUE_ACCESSOR],
  host: {
    '[attr.aria-disabled]': 'disabled()',
    '[class.ui-button-group-ng]': 'true',
    '[class.ui-button-group-ng--full-width]': 'fullWidth()',
    '[class.ui-button-group-ng--disabled]': 'disabled()',
  },
})
export class ButtonGroupComponent implements ControlValueAccessor {
  private el = inject(ElementRef<HTMLElement>);
  private destroyRef = inject(DestroyRef);

  // === CONTROL VALUE ACCESSOR ===

  private onChange: (value: string | string[] | null) => void = () => {};
  private onTouched: () => void = () => {};
  private isDisabled = false;

  // === SIGNAL INPUTS ===

  /** Variant inheritance for child buttons */
  variant = input<ButtonGroupVariant>('inherit');

  /** Size inheritance for child buttons */
  size = input<ButtonGroupSize>('inherit');

  /** Whether buttons are segmented */
  segmented = input<boolean>(false);

  /** Orientation of the button group */
  orientation = input<ButtonGroupOrientation>('horizontal');

  /** Gap between buttons */
  gap = input<'xs' | 'sm' | 'md' | 'lg' | 'none'>('md');

  /** Whether the group takes full width */
  fullWidth = input<boolean>(false);

  /** Whether the entire group is disabled */
  disabled = model<boolean>(false);

  /** Border radius size for the button group */
  rounded = input<ButtonRounded>('md');

  /** JSON string array of button objects with value, label, and optional button props */
  buttons = input<string>('');

  /** Selection mode for the button group */
  selectionMode = input<ButtonGroupSelectionMode>('none');

  // === BUTTON COMPONENT PROPS FOR INHERITANCE ===

  /** Whether child buttons are in loading state */
  buttonLoading = input<boolean>(false);

  /** Whether to enable click animation on child buttons (press effect) */
  buttonAnimated = input<boolean>(false);

  /** Whether child buttons should take full width */
  buttonFullWidth = input<boolean>(false);

  // === MODEL INPUT/OUTPUT ===

  /** Controlled value (selected button value(s)) */
  value = model<string | string[] | null>(null);

  // === OUTPUTS ===

  /** Emitted when selection changes */
  uiChange = output<ButtonGroupEventDetail>();

  /** Proxy for child button click events */
  uiClick = output<ButtonGroupEventDetail>();

  // === CONTENT CHILDREN ===

  /** Child button components */
  private buttonComponents = contentChildren(ButtonComponent);

  // === STATE ===

  private eventListeners: Array<{ event: string; handler: EventListener }> = [];

  // === LIFECYCLE ===

  constructor() {
    afterNextRender(() => {
      this.setupEventListeners();
    });

    inject(DestroyRef).onDestroy(() => {
      this.cleanupEventListeners();
    });
  }

  // === CONTROL VALUE ACCESSOR METHODS ===

  writeValue(value: string | string[] | null): void {
    this.value.set(value);
  }

  registerOnChange(fn: (value: string | string[] | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.isDisabled = isDisabled;
    this.disabled.set(isDisabled);
  }

  // === PRIVATE METHODS ===

  private setupEventListeners(): void {
    const buttonGroup = this.el.nativeElement.querySelector('ui-button-group');
    if (!buttonGroup) return;

    // Change event
    const changeHandler = (e: CustomEvent<ButtonGroupEventDetail>) => {
      this.uiChange.emit(e.detail);
      this.value.set(e.detail.value);
      this.onChange(e.detail.value);
      this.onTouched();
    };
    buttonGroup.addEventListener('uiChange', changeHandler as EventListener);

    // Click event
    const clickHandler = (e: CustomEvent<ButtonGroupEventDetail>) => {
      this.uiClick.emit(e.detail);
    };
    buttonGroup.addEventListener('uiClick', clickHandler as EventListener);

    // Cleanup on destroy using DestroyRef
    this.destroyRef.onDestroy(() => {
      buttonGroup.removeEventListener('uiChange', changeHandler as EventListener);
      buttonGroup.removeEventListener('uiClick', clickHandler as EventListener);
    });
  }

  private cleanupEventListeners = (): void => {
    const buttonGroup = this.el.nativeElement as HTMLElement & {
      removeEventListener: (
        event: string,
        handler: EventListener,
        options?: EventListenerOptions,
      ) => void;
    };

    this.eventListeners.forEach(({ event, handler }) => {
      buttonGroup.removeEventListener(event, handler);
    });

    this.eventListeners = [];
  };

  private syncPropsToWebComponent(): void {
    // Props are synced via template binding in button-group.component.html
  }

  private applyButtonProps(): void {
    const currentButtons = this.buttonComponents();

    currentButtons.forEach((button: ButtonComponent, index: number) => {
      // Get button value from element
      const buttonElement = button['el']?.nativeElement;
      if (!buttonElement) return;

      const buttonValue = buttonElement.getAttribute('value');

      // Apply size if not inherit
      if (this.size() !== 'inherit') {
        buttonElement.setAttribute('size', this.size());
      }

      // Apply disabled state
      if (this.disabled()) {
        buttonElement.setAttribute('disabled', 'true');
      }

      // Apply segmented styling
      if (this.segmented()) {
        this.applyAttachedStyles(buttonElement, index);
      }
    });
  }

  private applyAttachedStyles(buttonElement: HTMLElement, index: number): void {
    const total = this.buttonComponents().length;
    const isFirst = index === 0;
    const isLast = index === total - 1;

    if (total > 1) {
      if (isFirst) {
        buttonElement.setAttribute('data-position', 'first');
      } else if (isLast) {
        buttonElement.setAttribute('data-position', 'last');
      } else {
        buttonElement.setAttribute('data-position', 'middle');
      }
    }
  }

  // === COMPUTED CLASSES ===

  getGroupClasses(): string {
    const classes = [
      'ui-button-group',
    ];

    classes.push(`ui-button-group--${this.orientation()}`);

    if (this.fullWidth()) {
      classes.push('ui-button-group--full-width');
    }

    if (this.segmented()) {
      classes.push('ui-button-group--segmented');
    }

    classes.push(`ui-button-group--gap-${this.gap()}`);

    classes.push(`ui-button-group--rounded-${this.rounded()}`);

    return classes.join(' ');
  }

  getGroupRole(): string {
    return 'group';
  }

  getGroupAriaProps(): Record<string, string> {
    return {};
  }
}

/**
 * Directive for using ui-button-group on native elements
 * @usage <div uiButtonGroup orientation="horizontal" selectionMode="single">
 *   <button uiButton value="option1">Option 1</button>
 *   <button uiButton value="option2">Option 2</button>
 * </div>
 */
@Directive({
  selector: '[uiButtonGroup]',
  standalone: true,
  host: {
    '[attr.data-orientation]': 'orientation()',
    '[attr.data-variant]': 'variant()',
    '[attr.data-size]': 'size()',
    '[attr.data-segmented]': 'segmented()',
    '[attr.data-attached]': 'attached()',
    '[attr.data-full-width]': 'fullWidth()',
    '[attr.data-disabled]': 'disabled()',
    '[attr.data-selection-mode]': 'selectionMode()',
  },
})
export class UiButtonGroupDirective {
  orientation = input<ButtonGroupOrientation>('horizontal');
  variant = input<ButtonGroupVariant>('inherit');
  size = input<ButtonGroupSize>('inherit');
  segmented = input<boolean>(false);
  attached = input<boolean>(false);
  fullWidth = input<boolean>(false);
  disabled = input<boolean>(false);
  selectionMode = input<ButtonGroupSelectionMode>('none');
}

<ui-button-group
  [variant]="variant()"
  [size]="size()"
  [segmented]="segmented()"
  [orientation]="orientation()"
  [gap]="gap()"
  [fullWidth]="fullWidth()"
  [disabled]="disabled()"
  [rounded]="rounded()"
  [buttons]="buttons()"
  [buttonLoading]="buttonLoading()"
  [buttonAnimated]="buttonAnimated()"
  [buttonFullWidth]="buttonFullWidth()"
  [selectionMode]="selectionMode()"
  [value]="value()"
  [attr.role]="getGroupRole()"
  (uiChange)="uiChange.emit($event.detail)"
  (uiClick)="uiClick.emit($event.detail)"
  [class]="getGroupClasses()"
>
  <ng-content></ng-content>
</ui-button-group>
