// ui-platform/packages/angular/projects/ui-lib/src/lib/breadcrumb/breadcrumb.component.ts
import { Component, ChangeDetectionStrategy, input, output, ElementRef, inject, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

export interface BreadcrumbItem {
  value: string;
  label: string;
  href?: string;
  active?: boolean;
  disabled?: boolean;
  icon?: string;
}

@Component({
  selector: 'ui-breadcrumb-wrapper',
  standalone: true,
  templateUrl: './breadcrumb.component.html',
  styleUrls: ['./breadcrumb.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class UiBreadcrumbComponent {
  private hostElement = inject(ElementRef);

  // === INPUTS ===

  /** Breadcrumb items as JSON string */
  items = input('');

  /** Separator between items */
  separator = input<'slash' | 'chevron' | 'arrow' | string>('slash');

  /** Maximum number of items before collapsing */
  maxItems = input<number>();

  /** Number of items to show before collapse indicator */
  itemsBeforeCollapse = input<number>(1);

  /** Number of items to show after collapse indicator */
  itemsAfterCollapse = input<number>(1);

  /** Whether the breadcrumb is disabled */
  disabled = input(false);

  // === OUTPUTS ===

  /** Callback when a breadcrumb item is clicked */
  uiClick = output<{ value: string; index: number; href?: string }>();

  // === METHODS ===

  handleUiClick(event: CustomEvent): void {
    this.uiClick.emit(event.detail);
  }
}

<ui-breadcrumb
  [items]="items()"
  [separator]="separator()"
  [maxItems]="maxItems()"
  [itemsBeforeCollapse]="itemsBeforeCollapse()"
  [itemsAfterCollapse]="itemsAfterCollapse()"
  [disabled]="disabled()"
  (uiClick)="handleUiClick($event)"
>
</ui-breadcrumb>

// ui-platform/packages/react/src/components/breadcrumb/Breadcrumb.tsx
import React, { forwardRef, useEffect, useRef, useImperativeHandle } from 'react';

export interface UiBreadcrumbProps {
  /** Breadcrumb items as JSON string */
  items?: string;
  /** Separator between items */
  separator?: 'slash' | 'chevron' | 'arrow' | string;
  /** Maximum number of items before collapsing */
  maxItems?: number;
  /** Number of items to show before collapse indicator */
  itemsBeforeCollapse?: number;
  /** Number of items to show after collapse indicator */
  itemsAfterCollapse?: number;
  /** Whether the breadcrumb is disabled */
  disabled?: boolean;
  /** Callback when a breadcrumb item is clicked */
  onUiClick?: (detail: { value: string; index: number; href?: string }) => void;
  /** Additional CSS classes */
  className?: string;
  /** HTML data attributes */
  [key: `data-${string}`]: string | number | boolean | undefined;
}

export interface UiBreadcrumbRef {
  element: HTMLElement | null;
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'ui-breadcrumb': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        items?: string;
        separator?: 'slash' | 'chevron' | 'arrow' | string;
        maxItems?: number;
        itemsBeforeCollapse?: number;
        itemsAfterCollapse?: number;
        disabled?: boolean;
      };
    }
  }
}

export const Breadcrumb = forwardRef<UiBreadcrumbRef, UiBreadcrumbProps>(
  (
    {
      items = '',
      separator = 'slash',
      maxItems,
      itemsBeforeCollapse = 1,
      itemsAfterCollapse = 1,
      disabled = false,
      onUiClick,
      className,
      ...rest
    },
    ref,
  ) => {
    const innerRef = useRef<HTMLElement>(null);

    // Expose imperative handle
    useImperativeHandle(ref, () => ({
      element: innerRef.current,
    }));

    // Sync props to web component
    useEffect(() => {
      const el = innerRef.current as any;
      if (!el) return;

      el.items = items;
      el.separator = separator;
      if (maxItems !== undefined) el.maxItems = maxItems;
      el.itemsBeforeCollapse = itemsBeforeCollapse;
      el.itemsAfterCollapse = itemsAfterCollapse;
      el.disabled = disabled;
    }, [items, separator, maxItems, itemsBeforeCollapse, itemsAfterCollapse, disabled]);

    // Setup event listeners
    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;

      const handleUiClick = (event: CustomEvent) => {
        onUiClick?.(event.detail);
      };

      el.addEventListener('uiClick', handleUiClick);

      return () => {
        el.removeEventListener('uiClick', handleUiClick);
      };
    }, [onUiClick]);

    return React.createElement(
      'ui-breadcrumb' as any,
      {
        ref: innerRef,
        class: className,
        items,
        separator,
        maxItems,
        itemsBeforeCollapse,
        itemsAfterCollapse,
        disabled,
        ...rest,
      },
    );
  },
);

Breadcrumb.displayName = 'Breadcrumb';
