// ui-platform/packages/react/src/components/button/Button.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useCallback,
  type ReactNode,
  type MouseEvent as ReactMouseEvent,
} from "react";
import type {
  ButtonVariant,
  ButtonSize,
  ButtonRounded,
  ButtonEventDetail,
  IconName,
} from "@karan9186/core";

// === TYPES ===

export interface UiButtonProps {
  /** Button content */
  children?: ReactNode;

  /** Visual style variant */
  variant?: ButtonVariant;

  /** Size of the button */
  size?: ButtonSize;

  /** Whether the button is disabled */
  disabled?: boolean;

  /** Whether the button is in loading state */
  loading?: boolean;

  /** Whether the button should take full width */
  fullWidth?: boolean;

  /** Whether to enable click animation */
  animated?: boolean;

  /** Border radius size */
  rounded?: ButtonRounded;

  /** Icon name for left side (from lucide icons) */
  iconLeft?: IconName;

  /** Icon name for right side (from lucide icons) */
  iconRight?: IconName;

  /** Icon name for center (for icon-only buttons) */
  icon?: IconName;

  /** Click event handler */
  onUiClick?: (detail: ButtonEventDetail) => void;

  /** Focus event handler */
  onUiFocus?: () => void;

  /** Blur event handler */
  onUiBlur?: () => void;

  /** Native click handler (for compatibility) */
  onClick?: (e: ReactMouseEvent<HTMLButtonElement>) => void;

  /** Additional CSS classes */
  className?: string;

  /** HTML data attributes */
  [key: `data-${string}`]: string | number | boolean | undefined;
}

export interface UiButtonRef {
  /** Reference to the underlying ui-button element */
  readonly element: HTMLElement | null;
  /** Focus the button */
  focus: () => void;
  /** Blur the button */
  blur: () => void;
  /** Click the button programmatically */
  click: () => void;
}

// === COMPONENT ===

/**
 * React Button Component
 * Modern wrapper around ui-button web component
 *
 * @example
 * ```tsx
 * <UiButton
 *   variant="default"
 *   size="md"
 *   onUiClick={(detail) => console.log('Clicked!', detail)}
 * >
 *   <span slot="icon-left">👈</span>
 *   Click Me
 *   <span slot="icon-right">👉</span>
 * </UiButton>
 * ```
 */
export const UiButton = forwardRef<UiButtonRef, UiButtonProps>(
  (
    {
      children,
      variant = "default",
      size = "default",
      disabled = false,
      loading = false,
      fullWidth = false,
      animated = false,
      rounded = 'md',
      iconLeft,
      iconRight,
      icon,
      onUiClick,
      onUiFocus,
      onUiBlur,
      onClick,
      className,
      ...rest
    },
    ref,
  ) => {
    const innerRef = useRef<HTMLElement>(null);

    // Expose imperative handle
    useImperativeHandle(ref, () => ({
      get element() {
        return innerRef.current;
      },
      focus: () => innerRef.current?.focus(),
      blur: () => innerRef.current?.blur(),
      click: () => innerRef.current?.click(),
    }));

    // Sync props to web component
    useEffect(() => {
      const el = innerRef.current as (HTMLElement & {
        variant?: string;
        size?: string;
        disabled?: boolean;
        loading?: boolean;
        fullWidth?: boolean;
        animated?: boolean;
        rounded?: string;
        iconLeft?: IconName;
        iconRight?: IconName;
        icon?: IconName;
      }) | null;
      if (!el) return;

      el.variant = variant;
      el.size = size;
      el.disabled = disabled;
      el.loading = loading;
      el.fullWidth = fullWidth;
      el.animated = animated;
      el.rounded = rounded;
      el.iconLeft = iconLeft;
      el.iconRight = iconRight;
      el.icon = icon;
    }, [variant, size, disabled, loading, fullWidth, animated, rounded, iconLeft, iconRight, icon]);

    // Event handlers with proper typing
    const handleClick = useCallback(
      (e: CustomEvent<ButtonEventDetail>) => {
        onUiClick?.(e.detail);
        // Also call native onClick for compatibility
        if (onClick) {
          const syntheticEvent = new MouseEvent("click") as unknown as ReactMouseEvent<HTMLButtonElement>;
          Object.defineProperty(syntheticEvent, "target", { value: innerRef.current });
          onClick(syntheticEvent);
        }
      },
      [onUiClick, onClick],
    );

    const handleFocus = useCallback(() => {
      onUiFocus?.();
    }, [onUiFocus]);

    const handleBlur = useCallback(() => {
      onUiBlur?.();
    }, [onUiBlur]);

    // Bind event listeners
    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;

      el.addEventListener("uiClick", handleClick as EventListener);
      el.addEventListener("uiFocus", handleFocus);
      el.addEventListener("uiBlur", handleBlur);

      return () => {
        el.removeEventListener("uiClick", handleClick as EventListener);
        el.removeEventListener("uiFocus", handleFocus);
        el.removeEventListener("uiBlur", handleBlur);
      };
    }, [handleClick, handleFocus, handleBlur]);

    return (
      <ui-button
        ref={innerRef}
        className={className}
        {...rest}
      >
        {children}
      </ui-button>
    );
  },
);

UiButton.displayName = "UiButton";

// === HOOK UTILITY ===

/**
 * Hook for using button functionality in React components
 * @returns Object with button ref and helper methods
 */
export function useButton() {
  const ref = useRef<UiButtonRef>(null);

  return {
    ref,
    focus: () => ref.current?.focus(),
    blur: () => ref.current?.blur(),
    click: () => ref.current?.click(),
  };
}

// ui-platform/packages/angular/projects/ui-lib/src/lib/button/button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  Directive,
  ElementRef,
  forwardRef,
  inject,
  input,
  model,
  OnDestroy,
  OnInit,
  output,
  Provider,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { ensureCustomElements } from '../register-custom-elements';
import type {
  ButtonVariant,
  ButtonSize,
  ButtonRounded,
  ButtonEventDetail,
  IconName,
} from '@karan9186/core';

ensureCustomElements();

// === PROVIDER FACTORY ===
export const UI_BUTTON_VALUE_ACCESSOR: Provider = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => ButtonComponent),
  multi: true,
};

/**
 * Modern Angular Button Component
 * Standalone component with signals-based inputs/outputs
 * Wraps ui-button web component
 *
 * @usage
 * <ui-button-angular
 *   variant="default"
 *   size="md"
 *   [disabled]="isDisabled"
 *   [loading]="isLoading"
 *   [animated]="true"
 *   rounded="lg"
 *   (uiClick)="handleClick($event)"
 * >
 *   <span icon-left><lucide-icon name="plus"></lucide-icon></span>
 *   Click Me
 *   <span icon-right><lucide-icon name="arrow-right"></lucide-icon></span>
 * </ui-button-angular>
 */
@Component({
  selector: 'ui-button-angular',
  templateUrl: './button.component.html',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [UI_BUTTON_VALUE_ACCESSOR],
  host: {
    '[attr.aria-disabled]': 'disabled()',
    '[class.ui-button-ng]': 'true',
    '[class.ui-button-ng--full-width]': 'fullWidth()',
    '[class.ui-button-ng--loading]': 'loading()',
    '[class.ui-button-ng--disabled]': 'disabled()',
  },
})
export class ButtonComponent implements ControlValueAccessor, OnInit, OnDestroy {
  private el = inject(ElementRef<HTMLElement>);
  private onChange: (value: unknown) => void = () => {};
  private onTouched: () => void = () => {};
  private eventListeners: (() => void)[] = [];

  // === SIGNAL INPUTS ===

  /** Visual style variant */
  variant = input<ButtonVariant>('default');

  /** Size of the button */
  size = input<ButtonSize>('default');

  /** Whether the button is disabled */
  disabled = model<boolean>(false);

  /** Whether the button is in loading state */
  loading = model<boolean>(false);

  /** Whether the button should take full width */
  fullWidth = input<boolean>(false);

  /** Whether to enable click animation */
  animated = input<boolean>(false);

  /** Border radius size */
  rounded = input<ButtonRounded>('md');

  /** Icon name for left side (from lucide icons) */
  iconLeft = input<IconName | undefined>(undefined);

  /** Icon name for right side (from lucide icons) */
  iconRight = input<IconName | undefined>(undefined);

  /** Icon name for center (for icon-only buttons) */
  icon = input<IconName | undefined>(undefined);

  // === OUTPUTS ===

  /** Emitted when button is clicked */
  uiClick = output<ButtonEventDetail>();

  /** Emitted when button receives focus */
  uiFocus = output<void>();

  /** Emitted when button loses focus */
  uiBlur = output<void>();

  // === LIFECYCLE ===

  ngOnInit(): void {
    this.setupEventListeners();
    this.syncPropsToWebComponent();
  }

  ngOnDestroy(): void {
    this.eventListeners.forEach((remove) => remove());
  }

  // === CONTROL VALUE ACCESSOR ===

  writeValue(value: unknown): void {
    // Button doesn't have a value, but we implement this for form integration
    // Could be used for toggle buttons in the future
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  // === PRIVATE METHODS ===

  private setupEventListeners(): void {
    const button = this.el.nativeElement.querySelector('ui-button');
    if (!button) return;

    // Click event
    const clickHandler = (e: CustomEvent<ButtonEventDetail>) => {
      this.onTouched();
      this.uiClick.emit(e.detail);
      this.onChange(true); // Signal that button was clicked
    };
    button.addEventListener('uiClick', clickHandler as EventListener);
    this.eventListeners.push(() =>
      button.removeEventListener('uiClick', clickHandler as EventListener)
    );

    // Focus event
    const focusHandler = () => this.uiFocus.emit();
    button.addEventListener('uiFocus', focusHandler);
    this.eventListeners.push(() =>
      button.removeEventListener('uiFocus', focusHandler)
    );

    // Blur event
    const blurHandler = () => {
      this.onTouched();
      this.uiBlur.emit();
    };
    button.addEventListener('uiBlur', blurHandler);
    this.eventListeners.push(() =>
      button.removeEventListener('uiBlur', blurHandler)
    );
  }

  private syncPropsToWebComponent(): void {
    // Props are synced via template binding in button.component.html
  }
}

/**
 * Directive for using ui-button on native button elements
 * @usage <button uiButton variant="default" size="md">Click Me</button>
 */
@Directive({
  selector: 'button[uiButton], a[uiButton]',
  standalone: true,
  host: {
    '[attr.data-variant]': 'variant()',
    '[attr.data-size]': 'size()',
    '[attr.data-disabled]': 'disabled()',
    '[attr.data-loading]': 'loading()',
    '[attr.data-animated]': 'animated()',
    '[attr.data-rounded]': 'rounded()',
  },
})
export class UiButtonDirective {
  variant = input<ButtonVariant>('default');
  size = input<ButtonSize>('default');
  disabled = input<boolean>(false);
  loading = input<boolean>(false);
  animated = input<boolean>(false);
  rounded = input<ButtonRounded>('md');
  iconLeft = input<IconName | undefined>(undefined);
  iconRight = input<IconName | undefined>(undefined);
  icon = input<IconName | undefined>(undefined);
}

<ui-button
  [variant]="variant()"
  [size]="size()"
  [disabled]="disabled()"
  [loading]="loading()"
  [fullWidth]="fullWidth()"
  [animated]="animated()"
  [rounded]="rounded()"
  [iconLeft]="iconLeft()"
  [iconRight]="iconRight()"
  [icon]="icon()"
  (uiClick)="uiClick.emit($event.detail)"
  (uiFocus)="uiFocus.emit()"
  (uiBlur)="uiBlur.emit()"
>
  <!-- Left icon slot -->
  <ng-content select="[icon-left]" slot="icon-left"></ng-content>

  <!-- Default content slot -->
  <ng-content></ng-content>

  <!-- Right icon slot -->
  <ng-content select="[icon-right]" slot="icon-right"></ng-content>
</ui-button>
